### ISSUE TITLE
New windows reuse tabs from closed windows

### ISSUE THREAD

**Issue by jlabonski** [wmertens/global-chrome-tab#2]
If you close a tabbed window and the use the global shortcut to open a new window, you get the closed window with all of its tabs back.

This seems to be an artifact of Chrome 64's (I think) addition of setSelfAsOpener.

I've done some refactoring and added in the option, seems to WorkForMe® on MacOS. 
https://github.com/jlabonski/global-chrome-tab/commits/master

**Comment by wmertens** [comment]
Cool, looks good, thanks! I'll get it merged later this week

**Comment by jlabonski** [comment]
Take it for a bit of a spin first. At first the behavior was a bit baffling (and I'm no Chrome developer). I _think_ that if you create a new window with the extension, add tabs, close it, then create another one with the extension it inherits the browsing environment of the previous window. The parent of both windows is the extension's `background.js`.

At least I think so. There's some code in there to forcibly zap tabs in new windows, but I never get a tabs.length greater than 1, even if there's a dozen tabs staring me in the face.

**Comment by wmertens** [comment]
weird. I must say, I only open new windows (not like back when I picked the name for the extension 😉), so I didn't notice this before. I'll have to investigate.

**Comment by wmertens** [comment]
I'm having trouble reproducing this in v78 - I assume it fixed itself?

**Comment by jlabonski** [comment]
I've gone over to the dark side and basically do this via OS scripting. Feel free to close.

**Comment by wmertens** [comment]
Lol I used to do this with Applescript but with an extension it was faster ;)

**Comment by RogerThiede** [comment]
Could this be related to the Google Chrome setting “On Startup - Continue
where you left off”?

**Comment by wmertens** [comment]
:thinking: I don't think so - closing the last window doesn't close the application on macOS, so it wouldn't be starting up. And actually the shortcut wouldn't work either ;)
