### ISSUE TITLE
All options are inaccessible

### ISSUE THREAD

**Issue by RogerThiede** [wmertens/global-chrome-tab#3]
Unable to open the options pane or set/modify any options of this extension.

> Global New Tab Shortcut
> Options          <--- This is disabled/greyed out
> Remove from Chrome...
> Show in Toolbar
> Manage Extensions

Chrome Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by wmertens** [comment]
Actually, there is no option panel. You can only choose the shortcuts via the "keyboard shortcuts" section of the extensions, in chrome://extensions/shortcuts

**Comment by wmertens** [comment]
Closing, let me know if you still have trouble
