### ISSUE TITLE
Where is the api or possible commands that can be used in the Code?

### ISSUE THREAD

**Issue by jddcef** [wmertens/global-chrome-tab#5]
Hi, I don't see where the commands are like to "switch to tab", or to enter a new search in a new tab etc?

I don't see why this is called  a global new tab shortcut if the shortcuts don't really do anything except execute an empty code block?

**Comment by wmertens** [comment]
I'm not sure what you mean, the commands are defined in https://github.com/wmertens/global-chrome-tab/blob/master/background.js

When you install the extension, you can attach keyboard shortcuts to the commands and set them global so they work outside of Chrome (when Chrome is running)

**Comment by jddcef** [comment]
I see, so in the Code section of a shortcut, one can use `new-tab`, or it `new-tab()` ?
There's no documentation on the syntax, esp in the plugin's window where one is setting up the shortcut.

I was actually looking for a way to switch to tab, and the send the keys (shift-T), so I can open Vimium's tab search, so I can switch an open tab that is open somewhere amongst all the tabs and windows.

**Comment by wmertens** [comment]
ah ok - this extension is only for setting up keyboard shortcuts, it's not addding vimium commands.
Also, I don't think it makes sense as a Vimium command, since it's for opening chrome while in other applications. So I'll close this issue.

**Comment by wmertens** [comment]
ah ok - this extension is only for setting up keyboard shortcuts, it's not addding vimium commands.
Also, I don't think it makes sense as a Vimium command, since it's for opening chrome while in other applications. So I'll close this issue.
